
- name: Configuration of master node
  hosts: localhost
  connection: local
  tasks:
    - name: initialize K8S cluster
      shell: sudo kubeadm init --pod-network-cidr=172.16.0.0/16 --apiserver-advertise-address=192.168.200.5 --ignore-preflight-errors=all

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
